version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=postgres_db
      - DB_NAME=medicamentos_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_PORT=5432
      - FLASK_APP=app.py
      - FLASK_SECRET_KEY=AE12m@kA1f6xaXdWc@KoA#a82ZUb#jvy6jeP25@yiIPDI3ZdaT # MUDE ISTO!
    networks:
     - new-infra_home-network

networks:
  new-infra_home-network:
    external: true
    driver: bridge
